# Endless repos: https://pre-commit.com/hooks.html

# Note that these don't run our tests - execute the 'tox' command from this directory to do that.
#
# The simple reason is 'commits should be fast and running all tests is slow' - https://github.com/pre-commit/pre-commit-hooks/issues/291.

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -  id: check-ast
       files: ^autocomplete/code_understanding/typing #/autocomplete/typing
       exclude: ^(autocomplete/code_understanding/typing/[examples|scratch.py|grammar.py])
    -  id: flake8
       files: ^autocomplete/code_understanding/typing #/autocomplete/typing
       exclude: ^(autocomplete/code_understanding/typing/[examples|scratch.py|grammar.py])
       args:
       - --ignore=D203,D212,D213,D404,E111,W0311,D107,D213,D211,C0111,E114,E302,E501,D101,D105,D102,W0212,D103,E261,E125,C0330,D100,C0301,W0511,D205,D209,R0201,E1135,E1136,E1137,W504,E124
    -  id: trailing-whitespace
