# (generated with --quick)

from typing import Any

_context_list: list
_context_prefix: str
inspect: module
item: str
logging: Any

def debug(message, *args, log = ..., **kwargs) -> None: ...
def error(message, *args, log = ..., **kwargs) -> None: ...
def info(message, *args, log = ..., **kwargs) -> None: ...
def log(level, message, *args, **kwargs) -> None: ...
def log_freq(level, message, log = ..., n_seconds = ...) -> None: ...
def pop_context() -> None: ...
def push_context(value) -> None: ...
def set_verbosity(level) -> None: ...
def warning(message, *args, log = ..., **kwargs) -> None: ...
