# (generated with --quick)

import inspect
import types
from typing import List, Union

class AmbiguousFuzzyValueError(Exception): ...

class AstUnableToParse(Exception): ...

class CellValueNotSetError(Exception): ...

class InvalidModuleError(Exception): ...

class LoadingModuleAttributeError(Exception): ...

class NoDictImplementationError(Exception): ...

class ParsingError(Exception): ...

class SourceAttributeError(Exception): ...

class UnableToReadModuleFileError(Exception): ...

def assert_unexpected_parso(assertion, *error) -> None: ...
def getframeinfo(frame: Union[types.FrameType, types.TracebackType], context: int = ...) -> inspect.`namedtuple-Traceback-0`: ...
def stack(context: int = ...) -> List[inspect.`namedtuple-FrameInfo-0`]: ...
