# (generated with --quick)

from typing import Any, Callable, Generator, List, Sequence

PYTHON2_EXCLUSIVE_BUILTINS: List[str]
itertools: module
sys: module

def assert_expected_iterable(actual, expected) -> None: ...
def assert_returns_type(type_) -> Callable[[Any], Any]: ...
def attrs_names_from_class(class_) -> Generator[Any, Any, None]: ...
def get_possible_builtin_symbols() -> itertools.chain[nothing]: ...
def instance_memoize(func) -> Callable: ...
def print_tree(node, indent = ..., file = ...) -> None: ...
def to_dict_iter(obj) -> Any: ...
def wraps(wrapped: Callable, assigned: Sequence[str] = ..., updated: Sequence[str] = ...) -> Callable[[Callable], Callable]: ...
